### ISSUE TITLE
sdnbridge + flannel in host-gw mode: wrong endpoint default gateway

### ISSUE THREAD

**Issue by adelina-t** [microsoft/windows-container-networking#40]
Using config: https://paste.ubuntu.com/p/c8YmjnjSSs/

Pods don't communicate across nodes in a scenario using flannel in host-gw mode + sdnbridge . I've noticed that sdnbridge sets the endpoint default gateway to x.y.z.1 however, it seems it should be x.y.z.2 ( at least that is what a similar setup using win-bridge does: https://github.com/containernetworking/plugins/blob/master/plugins/main/windows/win-bridge/win-bridge_windows.go#L82-L83 ).

Setting gateway via IPAM is not possible, as flannel does not allow custom ipam field when using delegate: https://github.com/containernetworking/plugins/blob/master/plugins/meta/flannel/flannel.go#L206-L208

I've tested with x.y.z.2 gateway on endpoints and it seems networking works across nodes.

**Comment by dineshgovindasamy** [comment]
@madhanrm @nagiesek Can you guys take a look please?

**Comment by nagiesek** [comment]
I'll close this out today.

**Comment by nagiesek** [comment]
Actually, I'll bring this up in the cni meeting tomorrow. I think it would be better to fix it there.

**Comment by daschott** [comment]
@nagiesek can this be closed? Where did the fix end up going?

**Comment by nagiesek** [comment]
Closing this, as it should be fixed. Let me know if the issue still occurs.
