### ISSUE TITLE
The v0.2.0 Alpha Release is outdated

### ISSUE THREAD

**Issue by doggy8088** [microsoft/windows-container-networking#65]
Due to this issue https://github.com/microsoft/Windows-Containers/issues/210, I think the `v0.2.0` release is really outdated. Would you please update the latest version to the [Release](https://github.com/microsoft/windows-container-networking/releases) of this repo?

**Comment by doggy8088** [comment]
@daschott @cwilhit

**Comment by cwilhit** [comment]
@Keith-Mange fyi

**Comment by debj1t** [comment]
Created the latest release:
https://github.com/microsoft/windows-container-networking/releases/tag/v0.3.0
